--- #YAML:1.0
name:               BDB-Wrapper
version:            0.53
abstract:           The module to use BerkeleyDB.pm with good option easily
author:
    - Hajime Kurita
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    BerkeleyDB:  0
    File::Spec:  0
    Test:    0
    Test::More: 0

no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
